config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dishes
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:dish_id/create"  => "favorites#create"
  delete "favorites/:dish_id/destroy" => "favorites#destroy"
  resources :notifications, only: :index
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :logs, only: [:create, :destroy]
  get :lists, to: 'lists#index'
  post   "lists/:dish_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
      @log = Log.new
    end
  end

  def about
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "クックログとは？") %>
<div id="fh5co-about">
  <div class="container">
    <h1>クックログとは？</h1>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div id="fh5co-portfolio">
    <div class="container">
      <div class="col-md-9">
        <h3>みんなの料理 (<%= @feed_items.count %>)</h3>
        <%= render 'shared/feed' %>
      </div>
      <div class="col-md-3">
        <p><%= link_to "新しい料理を作る", new_dish_path, class: "btn btn-primary btn-lg btn-demo btn-record" %></p>
        <br>
        <p><%= link_to "みんなの料理をCSV出力", "#", class: "btn btn-primary btn-lg btn-demo btn-csv" %></p>
      </div>
    </div>
  </div>
<% else %>
  <header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <div class="display-t js-fullheight">
            <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
              <h1>毎日のお料理に、<br>写真やメモをつけて保存。</h1>
              <h2>今日のレシピ、もう迷わない！</h2>
              <p>
                <%= link_to 'クックログを始める', signup_path, class: "btn btn-primary btn-lg btn-demo" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<div id="fh5co-about">
  <div class="container">
    <h1>利用規約</h1>
  </div>
</div>