config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dishes
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:dish_id/create"  => "favorites#create"
  delete "favorites/:dish_id/destroy" => "favorites#destroy"
  resources :notifications, only: :index
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :logs, only: [:create, :destroy]
  get :lists, to: 'lists#index'
  post   "lists/:dish_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :dish_id, presence: true
  validates :variety, presence: true
  validates :from_user_id, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user

  def index
    # current_userに対する通知の集合を取得
    @notifications = current_user.notifications
    # 一度indexページを開いたら、ユーザーの「通知フラグ」を削除
    current_user.update_attribute(:notification, false)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% user = User.find(notification.from_user_id) %>
<% dish = Dish.find(notification.dish_id) %>
<li id="notification-<%= notification.id %>">
  <div>
    <% if notification.variety == 1 %>
      <p><%= notification.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
      <p class="notification-message">あなたの料理が<%= link_to user.name, user_path(user) %>さんにお気に入り登録されました。</p>
    <% elsif notification.variety == 2 %>
      <p><%= notification.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
      <p class="notification-message">あなたの料理に<%= link_to user.name, user_path(user) %>さんがコメントしました。
      「<%= notification.content %>」</p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= link_to((image_tag dish.picture.url), dish_path(dish), class: 'dish-picture') %>
    </div>
    <div class="col-md-7">
      <p><%= link_to dish.name, dish_path(dish) %></p>
      <p><%= dish.description %></p>
    </div>
  </div>
</li>

app/views/notifications/index.html.erb
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3>　通知一覧</h3>
      </div>
    </div>
    <% if @notifications.present? %>
      <ol class="notifications">
        <%= render @notifications %>
      </ol>
    <% end %>
  </div>
</div>